"use client";

import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Votre Partenaire de Confiance depuis 1988',
    'hero.subtitle': 'Solutions innovantes en construction, énergie, sécurité et services pour vos projets les plus ambitieux',
    'hero.cta': 'Découvrir nos services',
    'hero.contact': 'Nous contacter',
    
    // Reassurance
    'reassurance.experience': '35+ ans d\'expérience',
    'reassurance.countries': '9 pays présents',
    'reassurance.projects': '1000+ projets réalisés',
    'reassurance.clients': 'Clients internationaux',
    
    // Services
    'services.title': 'Nos Domaines d\'Expertise',
    'services.subtitle': 'Des solutions complètes et sur mesure pour répondre à tous vos besoins',
    'services.learnMore': 'En savoir plus',
    'services.construction.title': 'Construction & BTP',
    'services.construction.desc': 'Camps permanents et temporaires, structures acier, bâtiments préfabriqués, routes et infrastructures',
    'services.power.title': 'Génération d\'Énergie',
    'services.power.desc': 'Vente, installation et maintenance de générateurs et centrales électriques, systèmes automatiques',
    'services.security.title': 'Sécurité & Surveillance',
    'services.security.desc': 'Barrières, clôtures, systèmes de surveillance, équipements de protection et véhicules blindés',
    'services.supply.title': 'Fourniture & Équipements',
    'services.supply.desc': 'Engins, véhicules, équipements de chantier, mobilier et matériels techniques spécialisés',
    'services.services.title': 'Services & Maintenance',
    'services.services.desc': 'Restauration, entretien, gestion d\'installations, traitement de l\'eau et solutions réseau',
    'services.manpower.title': 'Ressources Humaines',
    'services.manpower.desc': 'Mise à disposition d\'ingénieurs, architectes, techniciens et profils spécialisés',
    
    // Team
    'team.title': 'Notre Équipe d\'Experts',
    'team.subtitle': 'Des professionnels qualifiés au service de vos projets',
    
    // Team members
    'team.roger.position': 'Directeur Général',
    'team.roger.department': 'Direction',
    'team.roger.description': 'Fondateur et dirigeant avec plus de 35 ans d\'expérience dans la gestion de projets internationaux.',
    'team.nayef.position': 'Directeur Général',
    'team.nayef.department': 'Direction', 
    'team.nayef.description': 'Co-dirigeant spécialisé dans le développement stratégique et l\'expansion internationale.',
    'team.micheline.position': 'Assistante de Direction',
    'team.micheline.department': 'Administration',
    'team.micheline.description': 'Responsable des ressources humaines et de l\'administration générale.',
    'team.remy.position': 'Responsable Relations Publiques',
    'team.remy.department': 'Communication',
    'team.remy.description': 'Gestion de l\'image corporate et des relations avec les médias et partenaires.',
    'team.sayed.position': 'Ingénieur en Chef',
    'team.sayed.department': 'Ingénierie',
    'team.sayed.description': 'Expert en études techniques, conception et supervision des projets de construction.',
    'team.hala.position': 'Architecte',
    'team.hala.department': 'Ingénierie',
    'team.hala.description': 'Conception architecturale et supervision des projets de bâtiments et infrastructures.',
    'team.joseph.position': 'Topographe',
    'team.joseph.department': 'Ingénierie',
    'team.joseph.description': 'Expert en relevés topographiques et cartographie pour les projets de construction.',
    'team.evelyne.position': 'Directrice Financière',
    'team.evelyne.department': 'Finance',
    'team.evelyne.description': 'Gestion financière, comptabilité et analyse des performances économiques.',
    'team.barkos.position': 'Superviseur de Chantier',
    'team.barkos.department': 'Opérations',
    'team.barkos.description': 'Supervision et coordination des travaux sur site, gestion de la sécurité.',
    'team.janine.position': 'Responsable Production',
    'team.janine.department': 'Opérations',
    'team.janine.description': 'Planification et coordination des processus de production et de livraison.',
    
    // About sections
    'about1.title': 'Notre Excellence au Service de Vos Défis',
    'about1.text1': 'Depuis plus de 35 ans, Derjani Solutions accompagne les entreprises dans leurs projets les plus ambitieux. Notre expertise reconnue dans les secteurs de l\'énergie, de la défense et des infrastructures nous permet d\'offrir des solutions innovantes et sur mesure.',
    'about1.text2': 'Présents dans 9 pays à travers le monde, nous combinons savoir-faire local et vision internationale pour répondre aux enjeux complexes de nos clients. Notre engagement : transformer vos défis en succès durables.',
    'about1.cta': 'En savoir plus',
    
    'about2.title': 'Innovation et Expertise Technique',
    'about2.text1': 'Notre équipe d\'experts combine technologies de pointe et méthodes éprouvées pour livrer des solutions performantes. Nous investissons continuellement dans la recherche et développement pour rester à la pointe de l\'innovation.',
    'about2.text2': 'De la conception à la mise en œuvre, nous accompagnons nos clients avec rigueur et créativité. Notre approche collaborative garantit des résultats qui dépassent les attentes et créent de la valeur durable.',
    'about2.cta': 'En savoir plus',
    
    // FAQ
    'faq.title': 'Questions les plus fréquentes',
    'faq.subtitle': 'Retrouvez les réponses aux questions les plus courantes concernant nos services, notre expertise et nos méthodes de travail. Notre équipe reste disponible pour toute question complémentaire.',
    'faq.cta': 'Nous contacter',
    'faq.q1': 'Quels sont vos domaines d\'expertise principaux ?',
    'faq.a1': 'Nous intervenons principalement dans les secteurs de l\'énergie, de la défense, des infrastructures et des services aux entreprises. Notre expertise couvre la logistique, l\'ingénierie, la maintenance industrielle et les solutions technologiques.',
    'faq.q2': 'Dans quels pays êtes-vous présents ?',
    'faq.a2': 'Derjani Solutions est présent dans 9 pays : Liban, Émirats Arabes Unis, Irak, Afghanistan, Tunisie, Koweït, Soudan du Sud, Nigeria. Cette présence internationale nous permet d\'accompagner nos clients sur leurs projets locaux et régionaux.',
    'faq.q3': 'Comment garantissez-vous la qualité de vos services ?',
    'faq.a3': 'Notre approche qualité repose sur des certifications internationales, des processus rigoureux et une équipe d\'experts expérimentés. Nous effectuons des contrôles réguliers et maintenons une démarche d\'amélioration continue pour assurer l\'excellence de nos prestations.',
    'faq.q4': 'Quels types de projets pouvez-vous gérer ?',
    'faq.a4': 'Nous gérons des projets de toutes tailles, depuis les missions ponctuelles jusqu\'aux programmes complexes multi-sites. Notre expérience nous permet d\'intervenir sur des projets d\'infrastructure, d\'exploitation pétrolière, de défense et de reconstruction post-conflit.',
    'faq.q5': 'Comment obtenir un devis pour mon projet ?',
    'faq.a5': 'Vous pouvez nous contacter directement via notre formulaire de contact ou par téléphone. Nos équipes commerciales étudieront votre cahier des charges et vous proposeront une solution adaptée avec un devis détaillé sous 48h.',
    
    // Trust Banner
    'trust.title': 'Ils nous ont fait confiance',
    'trust.subtitle': 'Des partenaires de renom qui ont choisi notre expertise',
    
    // Offices Map
    'offices.title': 'Nos Bureaux Internationaux',
    'offices.subtitle': 'Présents dans 9 pays pour servir nos clients partout dans le monde',
    'offices.select': 'Sélectionner un bureau',
    
    // Office locations
    'offices.beirut.name': 'Beyrouth',
    'offices.beirut.country': 'Liban',
    'offices.beirut.description': 'Siège social - Fondé en 1988',
    'offices.abudhabi.name': 'Abu Dhabi',
    'offices.abudhabi.country': 'Émirats Arabes Unis',
    'offices.abudhabi.description': 'Bureau régional Golfe',
    'offices.dubai.name': 'Dubaï',
    'offices.dubai.country': 'Émirats Arabes Unis',
    'offices.dubai.description': 'Centre commercial et logistique',
    'offices.baghdad.name': 'Bagdad',
    'offices.baghdad.country': 'Irak',
    'offices.baghdad.description': 'Operations militaires et reconstruction',
    'offices.kabul.name': 'Kaboul',
    'offices.kabul.country': 'Afghanistan',
    'offices.kabul.description': 'Support forces ISAF/OTAN',
    'offices.tunis.name': 'Tunis',
    'offices.tunis.country': 'Tunisie',
    'offices.tunis.description': 'Hub Afrique du Nord',
    'offices.kuwait.name': 'Koweït',
    'offices.kuwait.country': 'Koweït',
    'offices.kuwait.description': 'Services pétroliers et gaziers',
    'offices.juba.name': 'Juba',
    'offices.juba.country': 'Soudan du Sud',
    'offices.juba.description': 'Missions Nations Unies',
    'offices.lagos.name': 'Lagos',
    'offices.lagos.country': 'Nigeria',
    'offices.lagos.description': 'Industrie pétrolière',
    
    // Contact Form
    'contact.title': 'Nous contacter',
    'contact.text1': 'Vous avez un projet dans les domaines de la construction, la génération d\'énergie, la sécurité, ou les services ? Notre équipe d\'experts est à votre disposition pour étudier vos besoins et vous proposer des solutions adaptées.',
    'contact.text2': 'Forts de notre expérience depuis 1988 et de notre présence internationale, nous vous accompagnons de la conception à la réalisation de vos projets les plus ambitieux.',
    'contact.email': 'info@derjanigroup.com',
    'contact.location': 'Beyrouth, Liban - Siège social',
    'contact.guarantee': 'Réponse sous 48h garantie',
    'contact.form.title': 'Demande de devis',
    'contact.form.company': 'Entreprise',
    'contact.form.contact': 'Contact',
    'contact.form.contactName': 'Nom du contact',
    'contact.form.email': 'Email professionnel',
    'contact.form.phone': 'Téléphone',
    'contact.form.projectType': 'Type de projet',
    'contact.form.projectLocation': 'Localisation du projet',
    'contact.form.budget': 'Budget estimatif',
    'contact.form.timeline': 'Délais souhaités',
    'contact.form.description': 'Description du projet',
    'contact.form.submit': 'Demander un devis',
    'contact.form.submitting': 'Envoi en cours...',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.success': 'Demande de devis envoyée avec succès !',
    'contact.form.companyPlaceholder': 'Nom de votre entreprise',
    'contact.form.contactNamePlaceholder': 'Votre nom',
    'contact.form.emailPlaceholder': 'contact@entreprise.com',
    'contact.form.projectLocationPlaceholder': 'Pays, région',
    'contact.form.descriptionPlaceholder': 'Décrivez votre projet, vos besoins spécifiques, contraintes techniques, etc.',
    'contact.form.selectDomain': 'Sélectionnez un domaine',
    'contact.form.multiDomain': 'Projet multi-domaines',
    'contact.form.selectBudget': 'Budget approximatif',
    'contact.form.selectTimeline': 'Échéance du projet',
    
    // Form placeholders and options
    'form.company.placeholder': 'Nom de votre entreprise',
    'form.contact.placeholder': 'Votre nom',
    'form.email.placeholder': 'contact@entreprise.com',
    'form.phone.placeholder': '+33 1 23 45 67 89',
    'form.location.placeholder': 'Pays, région',
    'form.description.placeholder': 'Décrivez votre projet, vos besoins spécifiques, contraintes techniques, etc.',
    
    'form.projectType.select': 'Sélectionnez un domaine',
    'form.projectType.construction': 'Construction & BTP',
    'form.projectType.power': 'Génération d\'énergie',
    'form.projectType.security': 'Sécurité & Surveillance',
    'form.projectType.supply': 'Fourniture & Équipements',
    'form.projectType.services': 'Services & Maintenance',
    'form.projectType.manpower': 'Ressources humaines',
    'form.projectType.multiple': 'Projet multi-domaines',
    
    'form.budget.select': 'Budget approximatif',
    'form.budget.50k-200k': '50k€ - 200k€',
    'form.budget.200k-500k': '200k€ - 500k€',
    'form.budget.500k-1M': '500k€ - 1M€',
    'form.budget.1M-5M': '1M€ - 5M€',
    'form.budget.5M+': 'Plus de 5M€',
    
    'form.timeline.select': 'Échéance du projet',
    'form.timeline.urgent': 'Urgent (moins de 1 mois)',
    'form.timeline.1-3months': '1 à 3 mois',
    'form.timeline.3-6months': '3 à 6 mois',
    'form.timeline.6-12months': '6 à 12 mois',
    'form.timeline.12months+': 'Plus de 12 mois',
    
    // Navigation menu
    'nav.about.submenu': 'À propos',
    'nav.realizations.submenu': 'Réalisations', 
    'nav.commitments.submenu': 'Engagements',
    'nav.phone': '+33 1 23 45 67 89',
    
    // Megamenu - Services
    'megamenu.services.construction.name': 'Construction',
    'megamenu.services.construction.subtitle': 'Infrastructure & Bâtiment',
    'megamenu.services.construction.desc': 'Camps permanents et temporaires clé en main, structures acier, bâtiments Kspan, préfabriqués, routes, ponts, usines, centrales électriques, installations ferroviaires et hydrauliques',
    'megamenu.services.energie.name': 'Génération d\'énergie',
    'megamenu.services.energie.subtitle': 'Générateurs & Centrales',
    'megamenu.services.energie.desc': 'Vente, installation et maintenance de générateurs et centrales électriques, systèmes de démarrage automatique, panneaux de contrôle',
    'megamenu.services.securite.name': 'Sécurité',
    'megamenu.services.securite.subtitle': 'Protection & Surveillance',
    'megamenu.services.securite.desc': 'Barrières béton et acier, clôtures BRC, portails, tours de garde, systèmes de vidéosurveillance, véhicules blindés, équipements de protection',
    'megamenu.services.fourniture.name': 'Fourniture',
    'megamenu.services.fourniture.subtitle': 'Équipements & Véhicules',
    'megamenu.services.fourniture.desc': 'Grues, véhicules de transport, engins de chantier, équipements de buanderie, mobilier, systèmes d\'eau, équipements médicaux et électriques',
    'megamenu.services.services.name': 'Services',
    'megamenu.services.services.subtitle': 'Services techniques',
    'megamenu.services.services.desc': 'Restauration collective industrielle, entretien et maintenance, gestion des installations, traitement de l\'eau, aménagement paysager, solutions internet et réseaux',
    'megamenu.services.rh.name': 'Ressources humaines',
    'megamenu.services.rh.subtitle': 'Personnel qualifié',
    'megamenu.services.rh.desc': 'Ingénieurs civils et électriques, architectes, topographes, consultants, chefs exécutifs, techniciens spécialisés, main-d\'œuvre qualifiée',
    
    // Legal pages
    'legal.home': 'Accueil',
    'legal.mentions.title': 'Mentions Légales',
    'legal.mentions.description': 'Informations légales et réglementaires concernant Derjani Group',
    'legal.privacy.title': 'Politique de Confidentialité',
    'legal.privacy.description': 'Protection et respect de vos données personnelles',
    'legal.terms.title': 'Conditions Générales de Vente',
    'legal.terms.description': 'Nos conditions de vente et modalités contractuelles',
    
    // Single Service Pages
    'service.construction.hero.title': 'Construction & BTP',
    'service.construction.hero.subtitle': 'Solutions complètes pour vos projets de construction, camps permanents et temporaires, infrastructures',
    'service.construction.overview.title': 'Vue d\'ensemble du service',
    'service.construction.overview.text1': 'Forts de plus de 35 ans d\'expérience dans le secteur de la construction, nous proposons des solutions complètes et innovantes pour tous vos projets BTP. De la conception à la réalisation, notre expertise couvre l\'ensemble des métiers de la construction.',
    'service.construction.overview.text2': 'Nos équipes d\'ingénieurs, architectes et techniciens qualifiés interviennent sur des projets d\'envergure dans des environnements complexes, en respectant les plus hauts standards de qualité et de sécurité.',
    'service.construction.capabilities.title': 'Nos Capacités',
    'service.construction.capabilities.camps': 'Camps permanents et temporaires',
    'service.construction.capabilities.camps.desc': 'Conception et construction clé en main de bases vie complètes avec toutes commodités.',
    'service.construction.capabilities.structures': 'Structures acier et Kspan',
    'service.construction.capabilities.structures.desc': 'Bâtiments industriels et hangars avec structures métalliques sur mesure.',
    'service.construction.capabilities.prefab': 'Bâtiments préfabriqués',
    'service.construction.capabilities.prefab.desc': 'Solutions modulaires rapides à déployer pour besoins temporaires ou permanents.',
    'service.construction.capabilities.infrastructure': 'Routes et infrastructures',
    'service.construction.capabilities.infrastructure.desc': 'Travaux routiers, ponts, réseaux et aménagements urbains.',
    'service.construction.capabilities.industrial': 'Usines et centrales',
    'service.construction.capabilities.industrial.desc': 'Construction d\'installations industrielles et centrales électriques.',
    'service.construction.capabilities.specialized': 'Installations spécialisées',
    'service.construction.capabilities.specialized.desc': 'Projets ferroviaires, hydrauliques et installations techniques complexes.',
    'service.construction.process.title': 'Notre Processus',
    'service.construction.process.step1': 'Étude et conception',
    'service.construction.process.step1.desc': 'Analyse des besoins, études de faisabilité et conception détaillée.',
    'service.construction.process.step2': 'Planification',
    'service.construction.process.step2.desc': 'Planning détaillé, approvisionnements et mobilisation des équipes.',
    'service.construction.process.step3': 'Réalisation',
    'service.construction.process.step3.desc': 'Exécution des travaux avec suivi qualité et respect des délais.',
    'service.construction.process.step4': 'Livraison',
    'service.construction.process.step4.desc': 'Réception, formations et mise en service des installations.',
    'service.construction.expertise.title': 'Notre Expertise',
    'service.construction.expertise.experience': '35+ années d\'expérience',
    'service.construction.expertise.projects': '500+ projets réalisés',
    'service.construction.expertise.countries': '9 pays d\'intervention',
    'service.construction.expertise.team': '200+ experts qualifiés',

    // Service Power
    'service.power.hero.title': 'Génération d\'Énergie',
    'service.power.hero.subtitle': 'Solutions complètes en génération électrique, installation et maintenance de centrales',
    'service.power.overview.title': 'Solutions Énergétiques',
    'service.power.overview.text1': 'Spécialistes reconnus dans le domaine de la génération d\'énergie, nous fournissons des solutions complètes pour vos besoins électriques. De la conception à la maintenance, nous assurons une alimentation électrique fiable et continue.',
    'service.power.overview.text2': 'Notre expertise couvre tous les aspects de la génération électrique : vente d\'équipements, installation, mise en service, formation et maintenance préventive et curative.',
    'service.power.capabilities.title': 'Nos Solutions Énergétiques',
    'service.power.capabilities.generators': 'Générateurs électriques',
    'service.power.capabilities.generators.desc': 'Vente et installation de générateurs de toutes puissances pour besoins temporaires ou permanents.',
    'service.power.capabilities.powerplants': 'Centrales électriques',
    'service.power.capabilities.powerplants.desc': 'Construction et installation de centrales électriques complètes.',
    'service.power.capabilities.installation': 'Installation électrique',
    'service.power.capabilities.installation.desc': 'Raccordement et mise en service d\'installations électriques complexes.',
    'service.power.capabilities.maintenance': 'Maintenance préventive',
    'service.power.capabilities.maintenance.desc': 'Services de maintenance et réparation pour assurer la continuité électrique.',
    'service.power.capabilities.automation': 'Systèmes automatiques',
    'service.power.capabilities.automation.desc': 'Démarrage automatique et gestion intelligente des groupes électrogènes.',
    'service.power.capabilities.control': 'Panneaux de contrôle',
    'service.power.capabilities.control.desc': 'Systèmes de contrôle et de supervision pour optimiser la production électrique.',

    // Service Security
    'service.security.hero.title': 'Sécurité & Surveillance',
    'service.security.hero.subtitle': 'Protection complète avec systèmes de sécurité, surveillance et équipements de protection',
    'service.security.overview.title': 'Solutions de Sécurité',
    'service.security.overview.text1': 'La sécurité est au cœur de nos préoccupations. Nous proposons des solutions complètes de protection et de surveillance adaptées aux environnements les plus exigeants.',
    'service.security.overview.text2': 'Nos systèmes intègrent les dernières technologies de surveillance et de protection pour assurer la sécurité de vos installations et de vos équipes.',
    'service.security.capabilities.title': 'Nos Solutions de Sécurité',
    'service.security.capabilities.barriers': 'Barrières de protection',
    'service.security.capabilities.barriers.desc': 'Barrières béton et acier pour sécuriser les accès et délimiter les zones sensibles.',
    'service.security.capabilities.fencing': 'Clôtures et portails',
    'service.security.capabilities.fencing.desc': 'Clôtures BRC, portails automatiques et systèmes de contrôle d\'accès.',
    'service.security.capabilities.surveillance': 'Vidéosurveillance',
    'service.security.capabilities.surveillance.desc': 'Systèmes de caméras intelligentes avec vision nocturne et détection automatique.',
    'service.security.capabilities.vehicles': 'Véhicules blindés',
    'service.security.capabilities.vehicles.desc': 'Flotte de véhicules blindés pour transport sécurisé de personnel et matériel.',
    'service.security.capabilities.equipment': 'Équipements de protection',
    'service.security.capabilities.equipment.desc': 'Gilets pare-balles, casques et équipements de protection individuelle.',
    'service.security.capabilities.systems': 'Systèmes intégrés',
    'service.security.capabilities.systems.desc': 'Solutions de sécurité globales intégrant détection, alerte et intervention.',

    // Service Supply
    'service.supply.hero.title': 'Fourniture & Équipements',
    'service.supply.hero.subtitle': 'Approvisionnement en équipements, véhicules et matériels techniques spécialisés',
    'service.supply.overview.title': 'Fourniture d\'Équipements',
    'service.supply.overview.text1': 'Notre réseau mondial d\'approvisionnement nous permet de fournir rapidement tous types d\'équipements et de matériels techniques pour vos projets.',
    'service.supply.overview.text2': 'De la simple fourniture à la livraison clé en main, nous gérons l\'ensemble de la chaîne logistique pour répondre à vos besoins.',
    'service.supply.capabilities.title': 'Notre Catalogue d\'Équipements',
    'service.supply.capabilities.vehicles': 'Véhicules de transport',
    'service.supply.capabilities.vehicles.desc': 'Camions, véhicules utilitaires et de transport pour tous vos besoins logistiques.',
    'service.supply.capabilities.machinery': 'Engins de chantier',
    'service.supply.capabilities.machinery.desc': 'Grues, pelleteuses, bulldozers et équipements lourds pour travaux de terrassement.',
    'service.supply.capabilities.equipment': 'Équipements techniques',
    'service.supply.capabilities.equipment.desc': 'Outillage professionnel et équipements techniques spécialisés.',
    'service.supply.capabilities.furniture': 'Mobilier et aménagement',
    'service.supply.capabilities.furniture.desc': 'Mobilier de bureau, équipements de cantonnement et d\'aménagement.',
    'service.supply.capabilities.medical': 'Équipements médicaux',
    'service.supply.capabilities.medical.desc': 'Matériel médical d\'urgence et équipements de premiers secours.',
    'service.supply.capabilities.electrical': 'Matériel électrique',
    'service.supply.capabilities.electrical.desc': 'Composants électriques, câblage et systèmes de distribution électrique.',

    // Service Services
    'service.services.hero.title': 'Services & Maintenance',
    'service.services.hero.subtitle': 'Services techniques complets : restauration, maintenance et gestion d\'installations',
    'service.services.overview.title': 'Services Techniques',
    'service.services.overview.text1': 'Nos services techniques couvrent l\'ensemble des besoins opérationnels de vos installations : restauration collective, maintenance, gestion et services spécialisés.',
    'service.services.overview.text2': 'Une approche globale pour optimiser le fonctionnement de vos infrastructures et améliorer le confort de vos équipes.',
    'service.services.capabilities.title': 'Nos Services Techniques',
    'service.services.capabilities.catering': 'Restauration collective',
    'service.services.capabilities.catering.desc': 'Services de restauration industrielle et gestion de cuisines collectives.',
    'service.services.capabilities.maintenance': 'Maintenance technique',
    'service.services.capabilities.maintenance.desc': 'Maintenance préventive et curative de tous types d\'équipements.',
    'service.services.capabilities.management': 'Gestion d\'installations',
    'service.services.capabilities.management.desc': 'Facility management et gestion globale de sites industriels.',
    'service.services.capabilities.water': 'Traitement de l\'eau',
    'service.services.capabilities.water.desc': 'Systèmes de traitement et de purification d\'eau potable.',
    'service.services.capabilities.landscaping': 'Aménagement paysager',
    'service.services.capabilities.landscaping.desc': 'Entretien espaces verts et aménagements paysagers.',
    'service.services.capabilities.network': 'Solutions réseau',
    'service.services.capabilities.network.desc': 'Installation et maintenance de réseaux informatiques et internet.',

    // Service Manpower
    'service.manpower.hero.title': 'Ressources Humaines',
    'service.manpower.hero.subtitle': 'Mise à disposition d\'experts : ingénieurs, architectes, techniciens spécialisés',
    'service.manpower.overview.title': 'Expertise Humaine',
    'service.manpower.overview.text1': 'Notre réseau d\'experts qualifiés nous permet de mettre à votre disposition les compétences techniques dont vous avez besoin pour mener à bien vos projets.',
    'service.manpower.overview.text2': 'Ingénieurs, architectes, techniciens, consultants : nous sélectionnons les meilleurs profils pour répondre à vos exigences spécifiques.',
    'service.manpower.capabilities.title': 'Nos Expertises',
    'service.manpower.capabilities.engineers': 'Ingénieurs spécialisés',
    'service.manpower.capabilities.engineers.desc': 'Ingénieurs civils, électriques, mécaniques et spécialistes techniques.',
    'service.manpower.capabilities.architects': 'Architectes',
    'service.manpower.capabilities.architects.desc': 'Architectes expérimentés pour conception et supervision de projets.',
    'service.manpower.capabilities.technicians': 'Techniciens qualifiés',
    'service.manpower.capabilities.technicians.desc': 'Techniciens spécialisés dans tous les corps de métiers.',
    'service.manpower.capabilities.consultants': 'Consultants experts',
    'service.manpower.capabilities.consultants.desc': 'Conseillers et experts pour études et audits techniques.',
    'service.manpower.capabilities.chefs': 'Chefs exécutifs',
    'service.manpower.capabilities.chefs.desc': 'Professionnels de la restauration et management culinaire.',
    'service.manpower.capabilities.specialists': 'Spécialistes métiers',
    'service.manpower.capabilities.specialists.desc': 'Experts dans des domaines techniques très spécialisés.',

    // Common service elements
    'service.cta.title': 'Prêt à démarrer votre projet ?',
    'service.cta.subtitle': 'Contactez nos experts pour une étude personnalisée de vos besoins',
    'service.cta.button': 'Demander un devis',
    'service.related.title': 'Services Complémentaires',
    'service.breadcrumb.home': 'Accueil',
    'service.breadcrumb.services': 'Services',

    // Footer
    'footer.company': 'Derjani Solutions',
    'footer.description': 'Depuis 1988, nous accompagnons nos clients dans la réalisation de leurs projets les plus ambitieux à travers 9 pays.',
    'footer.services.title': 'Nos Services',
    'footer.offices.title': 'Nos Bureaux',
    'footer.offices.all': 'Voir tous nos bureaux →',
    'footer.contact.title': 'Contact',
    'footer.contact.email': 'info@derjanigroup.com',
    'footer.contact.location': 'Beyrouth, Liban',
    'footer.contact.cta': 'Nous contacter',
    'footer.copyright': '© 2024 Derjani Solutions. Tous droits réservés.',
    'footer.legal.mentions': 'Mentions légales',
    'footer.legal.privacy': 'Politique de confidentialité',
    'footer.legal.terms': 'CGV'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Your Trusted Partner Since 1988',
    'hero.subtitle': 'Innovative solutions in construction, energy, security and services for your most ambitious projects',
    'hero.cta': 'Discover our services',
    'hero.contact': 'Contact us',
    
    // Reassurance
    'reassurance.experience': '35+ years of experience',
    'reassurance.countries': '9 countries present',
    'reassurance.projects': '1000+ completed projects',
    'reassurance.clients': 'International clients',
    
    // Services
    'services.title': 'Our Areas of Expertise',
    'services.subtitle': 'Comprehensive and tailor-made solutions to meet all your needs',
    'services.learnMore': 'Learn more',
    'services.construction.title': 'Construction & Civil Works',
    'services.construction.desc': 'Permanent and temporary camps, steel structures, prefabricated buildings, roads and infrastructure',
    'services.power.title': 'Power Generation',
    'services.power.desc': 'Sale, installation and maintenance of generators and power plants, automatic systems',
    'services.security.title': 'Security & Surveillance',
    'services.security.desc': 'Barriers, fencing, surveillance systems, protective equipment and armored vehicles',
    'services.supply.title': 'Supply & Equipment',
    'services.supply.desc': 'Machinery, vehicles, construction equipment, furniture and specialized technical materials',
    'services.services.title': 'Services & Maintenance',
    'services.services.desc': 'Catering, maintenance, facility management, water treatment and network solutions',
    'services.manpower.title': 'Human Resources',
    'services.manpower.desc': 'Provision of engineers, architects, technicians and specialized profiles',
    
    // Team
    'team.title': 'Our Team of Experts',
    'team.subtitle': 'Qualified professionals at the service of your projects',
    
    // Team members
    'team.roger.position': 'General Manager',
    'team.roger.department': 'Management',
    'team.roger.description': 'Founder and leader with over 35 years of experience in international project management.',
    'team.nayef.position': 'General Manager',
    'team.nayef.department': 'Management',
    'team.nayef.description': 'Co-leader specialized in strategic development and international expansion.',
    'team.micheline.position': 'Executive Assistant',
    'team.micheline.department': 'Administration',
    'team.micheline.description': 'Responsible for human resources and general administration.',
    'team.remy.position': 'Public Relations Manager',
    'team.remy.department': 'Communication',
    'team.remy.description': 'Corporate image management and media and partner relations.',
    'team.sayed.position': 'Chief Engineer',
    'team.sayed.department': 'Engineering',
    'team.sayed.description': 'Expert in technical studies, design and supervision of construction projects.',
    'team.hala.position': 'Architect',
    'team.hala.department': 'Engineering',
    'team.hala.description': 'Architectural design and supervision of building and infrastructure projects.',
    'team.joseph.position': 'Surveyor',
    'team.joseph.department': 'Engineering',
    'team.joseph.description': 'Expert in topographic surveys and mapping for construction projects.',
    'team.evelyne.position': 'Financial Director',
    'team.evelyne.department': 'Finance',
    'team.evelyne.description': 'Financial management, accounting and economic performance analysis.',
    'team.barkos.position': 'Site Supervisor',
    'team.barkos.department': 'Operations',
    'team.barkos.description': 'Supervision and coordination of on-site work, safety management.',
    'team.janine.position': 'Production Manager',
    'team.janine.department': 'Operations',
    'team.janine.description': 'Planning and coordination of production and delivery processes.',
    
    // About sections
    'about1.title': 'Our Excellence at the Service of Your Challenges',
    'about1.text1': 'For over 35 years, Derjani Solutions has been supporting companies in their most ambitious projects. Our recognized expertise in the energy, defense and infrastructure sectors allows us to offer innovative and tailor-made solutions.',
    'about1.text2': 'Present in 9 countries around the world, we combine local know-how and international vision to respond to our clients\' complex challenges. Our commitment: transform your challenges into sustainable successes.',
    'about1.cta': 'Learn more',
    
    'about2.title': 'Innovation and Technical Expertise',
    'about2.text1': 'Our team of experts combines cutting-edge technologies and proven methods to deliver high-performance solutions. We continuously invest in research and development to stay at the forefront of innovation.',
    'about2.text2': 'From design to implementation, we support our clients with rigor and creativity. Our collaborative approach guarantees results that exceed expectations and create lasting value.',
    'about2.cta': 'Learn more',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to the most common questions about our services, expertise and working methods. Our team remains available for any additional questions.',
    'faq.cta': 'Contact us',
    'faq.q1': 'What are your main areas of expertise?',
    'faq.a1': 'We operate mainly in the energy, defense, infrastructure and business services sectors. Our expertise covers logistics, engineering, industrial maintenance and technological solutions.',
    'faq.q2': 'In which countries are you present?',
    'faq.a2': 'Derjani Solutions is present in 9 countries: Lebanon, United Arab Emirates, Iraq, Afghanistan, Tunisia, Kuwait, South Sudan, Nigeria. This international presence allows us to support our clients on their local and regional projects.',
    'faq.q3': 'How do you guarantee the quality of your services?',
    'faq.a3': 'Our quality approach is based on international certifications, rigorous processes and a team of experienced experts. We carry out regular checks and maintain a continuous improvement approach to ensure the excellence of our services.',
    'faq.q4': 'What types of projects can you manage?',
    'faq.a4': 'We manage projects of all sizes, from one-off missions to complex multi-site programs. Our experience allows us to work on infrastructure projects, oil exploitation, defense and post-conflict reconstruction.',
    'faq.q5': 'How to get a quote for my project?',
    'faq.a5': 'You can contact us directly via our contact form or by phone. Our sales teams will study your specifications and offer you a suitable solution with a detailed quote within 48 hours.',
    
    // Trust Banner
    'trust.title': 'They trusted us',
    'trust.subtitle': 'Renowned partners who chose our expertise',
    
    // Offices Map
    'offices.title': 'Our International Offices',
    'offices.subtitle': 'Present in 9 countries to serve our clients worldwide',
    'offices.select': 'Select an office',
    
    // Office locations
    'offices.beirut.name': 'Beirut',
    'offices.beirut.country': 'Lebanon',
    'offices.beirut.description': 'Headquarters - Founded in 1988',
    'offices.abudhabi.name': 'Abu Dhabi',
    'offices.abudhabi.country': 'United Arab Emirates',
    'offices.abudhabi.description': 'Gulf Regional Office',
    'offices.dubai.name': 'Dubai',
    'offices.dubai.country': 'United Arab Emirates',
    'offices.dubai.description': 'Commercial and logistics center',
    'offices.baghdad.name': 'Baghdad',
    'offices.baghdad.country': 'Iraq',
    'offices.baghdad.description': 'Military operations and reconstruction',
    'offices.kabul.name': 'Kabul',
    'offices.kabul.country': 'Afghanistan',
    'offices.kabul.description': 'ISAF/NATO forces support',
    'offices.tunis.name': 'Tunis',
    'offices.tunis.country': 'Tunisia',
    'offices.tunis.description': 'North Africa Hub',
    'offices.kuwait.name': 'Kuwait',
    'offices.kuwait.country': 'Kuwait',
    'offices.kuwait.description': 'Oil and gas services',
    'offices.juba.name': 'Juba',
    'offices.juba.country': 'South Sudan',
    'offices.juba.description': 'United Nations missions',
    'offices.lagos.name': 'Lagos',
    'offices.lagos.country': 'Nigeria',
    'offices.lagos.description': 'Oil industry',
    
    // Contact Form
    'contact.title': 'Contact us',
    'contact.text1': 'Do you have a project in construction, power generation, security, or services? Our team of experts is at your disposal to study your needs and propose suitable solutions.',
    'contact.text2': 'With our experience since 1988 and our international presence, we support you from design to completion of your most ambitious projects.',
    'contact.email': 'info@derjanigroup.com',
    'contact.location': 'Beirut, Lebanon - Headquarters',
    'contact.guarantee': 'Response within 48h guaranteed',
    'contact.form.title': 'Quote request',
    'contact.form.company': 'Company',
    'contact.form.contact': 'Contact',
    'contact.form.contactName': 'Contact name',
    'contact.form.email': 'Professional email',
    'contact.form.phone': 'Phone',
    'contact.form.projectType': 'Project type',
    'contact.form.projectLocation': 'Project location',
    'contact.form.budget': 'Estimated budget',
    'contact.form.timeline': 'Desired timeline',
    'contact.form.description': 'Project description',
    'contact.form.submit': 'Request a quote',
    'contact.form.submitting': 'Sending...',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Quote request sent successfully!',
    'contact.form.companyPlaceholder': 'Your company name',
    'contact.form.contactNamePlaceholder': 'Your name',
    'contact.form.emailPlaceholder': 'contact@company.com',
    'contact.form.projectLocationPlaceholder': 'Country, region',
    'contact.form.descriptionPlaceholder': 'Describe your project, specific needs, technical constraints, etc.',
    'contact.form.selectDomain': 'Select a field',
    'contact.form.multiDomain': 'Multi-domain project',
    'contact.form.selectBudget': 'Approximate budget',
    'contact.form.selectTimeline': 'Project timeline',
    
    // Form placeholders and options
    'form.company.placeholder': 'Your company name',
    'form.contact.placeholder': 'Your name',
    'form.email.placeholder': 'contact@company.com',
    'form.phone.placeholder': '+1 234 567 890',
    'form.location.placeholder': 'Country, region',
    'form.description.placeholder': 'Describe your project, specific needs, technical constraints, etc.',
    
    'form.projectType.select': 'Select a field',
    'form.projectType.construction': 'Construction & Civil Works',
    'form.projectType.power': 'Power Generation',
    'form.projectType.security': 'Security & Surveillance',
    'form.projectType.supply': 'Supply & Equipment',
    'form.projectType.services': 'Services & Maintenance',
    'form.projectType.manpower': 'Human Resources',
    'form.projectType.multiple': 'Multi-domain project',
    
    'form.budget.select': 'Approximate budget',
    'form.budget.50k-200k': '$50k - $200k',
    'form.budget.200k-500k': '$200k - $500k',
    'form.budget.500k-1M': '$500k - $1M',
    'form.budget.1M-5M': '$1M - $5M',
    'form.budget.5M+': 'Over $5M',
    
    'form.timeline.select': 'Project timeline',
    'form.timeline.urgent': 'Urgent (less than 1 month)',
    'form.timeline.1-3months': '1 to 3 months',
    'form.timeline.3-6months': '3 to 6 months',
    'form.timeline.6-12months': '6 to 12 months',
    'form.timeline.12months+': 'More than 12 months',
    
    // Navigation menu
    'nav.about.submenu': 'About',
    'nav.realizations.submenu': 'Projects',
    'nav.commitments.submenu': 'Commitments',
    'nav.phone': '+1 234 567 890',
    
    // Megamenu - Services
    'megamenu.services.construction.name': 'Construction',
    'megamenu.services.construction.subtitle': 'Infrastructure & Building',
    'megamenu.services.construction.desc': 'Permanent and temporary turnkey camps, steel structures, Kspan buildings, prefabricated, roads, bridges, factories, power plants, railway and hydraulic installations',
    'megamenu.services.energie.name': 'Power Generation',
    'megamenu.services.energie.subtitle': 'Generators & Power Plants',
    'megamenu.services.energie.desc': 'Sale, installation and maintenance of generators and power plants, automatic start systems, control panels',
    'megamenu.services.securite.name': 'Security',
    'megamenu.services.securite.subtitle': 'Protection & Surveillance',
    'megamenu.services.securite.desc': 'Concrete and steel barriers, BRC fencing, gates, guard towers, video surveillance systems, armored vehicles, protective equipment',
    'megamenu.services.fourniture.name': 'Supply',
    'megamenu.services.fourniture.subtitle': 'Equipment & Vehicles',
    'megamenu.services.fourniture.desc': 'Cranes, transport vehicles, construction equipment, laundry equipment, furniture, water systems, medical and electrical equipment',
    'megamenu.services.services.name': 'Services',
    'megamenu.services.services.subtitle': 'Technical services',
    'megamenu.services.services.desc': 'Industrial collective catering, maintenance and upkeep, facility management, water treatment, landscaping, internet and network solutions',
    'megamenu.services.rh.name': 'Human Resources',
    'megamenu.services.rh.subtitle': 'Qualified personnel',
    'megamenu.services.rh.desc': 'Civil and electrical engineers, architects, surveyors, consultants, executive chefs, specialized technicians, skilled labor',
    
    // Legal pages
    'legal.home': 'Home',
    'legal.mentions.title': 'Legal Notice',
    'legal.mentions.description': 'Legal and regulatory information about Derjani Group',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.description': 'Protection and respect of your personal data',
    'legal.terms.title': 'Terms and Conditions',
    'legal.terms.description': 'Our sales terms and contractual conditions',
    
    // Single Service Pages
    'service.construction.hero.title': 'Construction & Civil Works',
    'service.construction.hero.subtitle': 'Complete solutions for your construction projects, permanent and temporary camps, infrastructure',
    'service.construction.overview.title': 'Service Overview',
    'service.construction.overview.text1': 'With over 35 years of experience in the construction sector, we offer complete and innovative solutions for all your construction projects. From design to completion, our expertise covers all construction trades.',
    'service.construction.overview.text2': 'Our teams of qualified engineers, architects and technicians work on major projects in complex environments, respecting the highest quality and safety standards.',
    'service.construction.capabilities.title': 'Our Capabilities',
    'service.construction.capabilities.camps': 'Permanent and temporary camps',
    'service.construction.capabilities.camps.desc': 'Turnkey design and construction of complete living bases with all amenities.',
    'service.construction.capabilities.structures': 'Steel and Kspan structures',
    'service.construction.capabilities.structures.desc': 'Industrial buildings and hangars with custom metal structures.',
    'service.construction.capabilities.prefab': 'Prefabricated buildings',
    'service.construction.capabilities.prefab.desc': 'Quick-to-deploy modular solutions for temporary or permanent needs.',
    'service.construction.capabilities.infrastructure': 'Roads and infrastructure',
    'service.construction.capabilities.infrastructure.desc': 'Road works, bridges, networks and urban development.',
    'service.construction.capabilities.industrial': 'Factories and power plants',
    'service.construction.capabilities.industrial.desc': 'Construction of industrial facilities and power plants.',
    'service.construction.capabilities.specialized': 'Specialized installations',
    'service.construction.capabilities.specialized.desc': 'Railway, hydraulic and complex technical installation projects.',
    'service.construction.process.title': 'Our Process',
    'service.construction.process.step1': 'Study and design',
    'service.construction.process.step1.desc': 'Needs analysis, feasibility studies and detailed design.',
    'service.construction.process.step2': 'Planning',
    'service.construction.process.step2.desc': 'Detailed scheduling, procurement and team mobilization.',
    'service.construction.process.step3': 'Implementation',
    'service.construction.process.step3.desc': 'Work execution with quality monitoring and deadline compliance.',
    'service.construction.process.step4': 'Delivery',
    'service.construction.process.step4.desc': 'Reception, training and commissioning of installations.',
    'service.construction.expertise.title': 'Our Expertise',
    'service.construction.expertise.experience': '35+ years of experience',
    'service.construction.expertise.projects': '500+ completed projects',
    'service.construction.expertise.countries': '9 countries of operation',
    'service.construction.expertise.team': '200+ qualified experts',

    // Service Power
    'service.power.hero.title': 'Power Generation',
    'service.power.hero.subtitle': 'Complete electrical generation solutions, installation and maintenance of power plants',
    'service.power.overview.title': 'Energy Solutions',
    'service.power.overview.text1': 'Recognized specialists in power generation, we provide complete solutions for your electrical needs. From design to maintenance, we ensure reliable and continuous power supply.',
    'service.power.overview.text2': 'Our expertise covers all aspects of electrical generation: equipment sales, installation, commissioning, training and preventive and corrective maintenance.',
    'service.power.capabilities.title': 'Our Energy Solutions',
    'service.power.capabilities.generators': 'Electrical generators',
    'service.power.capabilities.generators.desc': 'Sale and installation of generators of all powers for temporary or permanent needs.',
    'service.power.capabilities.powerplants': 'Power plants',
    'service.power.capabilities.powerplants.desc': 'Construction and installation of complete power plants.',
    'service.power.capabilities.installation': 'Electrical installation',
    'service.power.capabilities.installation.desc': 'Connection and commissioning of complex electrical installations.',
    'service.power.capabilities.maintenance': 'Preventive maintenance',
    'service.power.capabilities.maintenance.desc': 'Maintenance and repair services to ensure electrical continuity.',
    'service.power.capabilities.automation': 'Automatic systems',
    'service.power.capabilities.automation.desc': 'Automatic start and intelligent management of generator sets.',
    'service.power.capabilities.control': 'Control panels',
    'service.power.capabilities.control.desc': 'Control and supervision systems to optimize electrical production.',

    // Service Security
    'service.security.hero.title': 'Security & Surveillance',
    'service.security.hero.subtitle': 'Complete protection with security systems, surveillance and protective equipment',
    'service.security.overview.title': 'Security Solutions',
    'service.security.overview.text1': 'Security is at the heart of our concerns. We offer complete protection and surveillance solutions adapted to the most demanding environments.',
    'service.security.overview.text2': 'Our systems integrate the latest surveillance and protection technologies to ensure the security of your facilities and teams.',
    'service.security.capabilities.title': 'Our Security Solutions',
    'service.security.capabilities.barriers': 'Protection barriers',
    'service.security.capabilities.barriers.desc': 'Concrete and steel barriers to secure access and delimit sensitive areas.',
    'service.security.capabilities.fencing': 'Fences and gates',
    'service.security.capabilities.fencing.desc': 'BRC fencing, automatic gates and access control systems.',
    'service.security.capabilities.surveillance': 'Video surveillance',
    'service.security.capabilities.surveillance.desc': 'Smart camera systems with night vision and automatic detection.',
    'service.security.capabilities.vehicles': 'Armored vehicles',
    'service.security.capabilities.vehicles.desc': 'Fleet of armored vehicles for secure transport of personnel and equipment.',
    'service.security.capabilities.equipment': 'Protective equipment',
    'service.security.capabilities.equipment.desc': 'Bulletproof vests, helmets and personal protective equipment.',
    'service.security.capabilities.systems': 'Integrated systems',
    'service.security.capabilities.systems.desc': 'Global security solutions integrating detection, alert and intervention.',

    // Service Supply
    'service.supply.hero.title': 'Supply & Equipment',
    'service.supply.hero.subtitle': 'Equipment supply, vehicles and specialized technical materials',
    'service.supply.overview.title': 'Equipment Supply',
    'service.supply.overview.text1': 'Our global supply network allows us to quickly provide all types of equipment and technical materials for your projects.',
    'service.supply.overview.text2': 'From simple supply to turnkey delivery, we manage the entire supply chain to meet your needs.',
    'service.supply.capabilities.title': 'Our Equipment Catalog',
    'service.supply.capabilities.vehicles': 'Transport vehicles',
    'service.supply.capabilities.vehicles.desc': 'Trucks, utility and transport vehicles for all your logistics needs.',
    'service.supply.capabilities.machinery': 'Construction machinery',
    'service.supply.capabilities.machinery.desc': 'Cranes, excavators, bulldozers and heavy equipment for earthwork.',
    'service.supply.capabilities.equipment': 'Technical equipment',
    'service.supply.capabilities.equipment.desc': 'Professional tools and specialized technical equipment.',
    'service.supply.capabilities.furniture': 'Furniture and fitting',
    'service.supply.capabilities.furniture.desc': 'Office furniture, accommodation and fitting equipment.',
    'service.supply.capabilities.medical': 'Medical equipment',
    'service.supply.capabilities.medical.desc': 'Emergency medical equipment and first aid equipment.',
    'service.supply.capabilities.electrical': 'Electrical material',
    'service.supply.capabilities.electrical.desc': 'Electrical components, wiring and electrical distribution systems.',

    // Service Services
    'service.services.hero.title': 'Services & Maintenance',
    'service.services.hero.subtitle': 'Complete technical services: catering, maintenance and facility management',
    'service.services.overview.title': 'Technical Services',
    'service.services.overview.text1': 'Our technical services cover all operational needs of your facilities: collective catering, maintenance, management and specialized services.',
    'service.services.overview.text2': 'A comprehensive approach to optimize the operation of your infrastructure and improve the comfort of your teams.',
    'service.services.capabilities.title': 'Our Technical Services',
    'service.services.capabilities.catering': 'Collective catering',
    'service.services.capabilities.catering.desc': 'Industrial catering services and collective kitchen management.',
    'service.services.capabilities.maintenance': 'Technical maintenance',
    'service.services.capabilities.maintenance.desc': 'Preventive and corrective maintenance of all types of equipment.',
    'service.services.capabilities.management': 'Facility management',
    'service.services.capabilities.management.desc': 'Facility management and global management of industrial sites.',
    'service.services.capabilities.water': 'Water treatment',
    'service.services.capabilities.water.desc': 'Drinking water treatment and purification systems.',
    'service.services.capabilities.landscaping': 'Landscaping',
    'service.services.capabilities.landscaping.desc': 'Green space maintenance and landscaping.',
    'service.services.capabilities.network': 'Network solutions',
    'service.services.capabilities.network.desc': 'Installation and maintenance of computer and internet networks.',

    // Service Manpower
    'service.manpower.hero.title': 'Human Resources',
    'service.manpower.hero.subtitle': 'Provision of experts: engineers, architects, specialized technicians',
    'service.manpower.overview.title': 'Human Expertise',
    'service.manpower.overview.text1': 'Our network of qualified experts allows us to provide you with the technical skills you need to successfully complete your projects.',
    'service.manpower.overview.text2': 'Engineers, architects, technicians, consultants: we select the best profiles to meet your specific requirements.',
    'service.manpower.capabilities.title': 'Our Expertise',
    'service.manpower.capabilities.engineers': 'Specialized engineers',
    'service.manpower.capabilities.engineers.desc': 'Civil, electrical, mechanical engineers and technical specialists.',
    'service.manpower.capabilities.architects': 'Architects',
    'service.manpower.capabilities.architects.desc': 'Experienced architects for project design and supervision.',
    'service.manpower.capabilities.technicians': 'Qualified technicians',
    'service.manpower.capabilities.technicians.desc': 'Technicians specialized in all trades.',
    'service.manpower.capabilities.consultants': 'Expert consultants',
    'service.manpower.capabilities.consultants.desc': 'Advisors and experts for technical studies and audits.',
    'service.manpower.capabilities.chefs': 'Executive chefs',
    'service.manpower.capabilities.chefs.desc': 'Catering professionals and culinary management.',
    'service.manpower.capabilities.specialists': 'Trade specialists',
    'service.manpower.capabilities.specialists.desc': 'Experts in highly specialized technical fields.',

    // Common service elements
    'service.cta.title': 'Ready to start your project?',
    'service.cta.subtitle': 'Contact our experts for a personalized study of your needs',
    'service.cta.button': 'Request a quote',
    'service.related.title': 'Complementary Services',
    'service.breadcrumb.home': 'Home',
    'service.breadcrumb.services': 'Services',

    // Footer
    'footer.company': 'Derjani Solutions',
    'footer.description': 'Since 1988, we have been supporting our clients in achieving their most ambitious projects across 9 countries.',
    'footer.services.title': 'Our Services',
    'footer.offices.title': 'Our Offices',
    'footer.offices.all': 'See all our offices →',
    'footer.contact.title': 'Contact',
    'footer.contact.email': 'info@derjanigroup.com',
    'footer.contact.location': 'Beirut, Lebanon',
    'footer.contact.cta': 'Contact us',
    'footer.copyright': '© 2024 Derjani Solutions. All rights reserved.',
    'footer.legal.mentions': 'Legal notice',
    'footer.legal.privacy': 'Privacy policy',
    'footer.legal.terms': 'Terms & Conditions'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};